src/Index/Repository/Document/DocumentRepository.php

ESPP-642 Remove dd()

---

src/Category/OpenApi/CategoryDecorator.php
src/Index/OpenApi/IndexDecorator.php
src/Index/Resources/config/services.yaml
src/OpenApi/Helper/Documentation.php
src/Product/OpenApi/ProductDecorator.php
src/Product/Resources/config/services.yaml
src/Search/OpenApi/SearchDecorator.php
src/Search/Resources/config/services.yaml
src/Security/OpenApi/JwtDecorator.php
src/Security/Resources/config/services.yaml

ESPP-649 Hide endpoints from swagger documentation

---

src/Configuration/Resources/config/api_platform.yaml

ESPP-650 Remove the spider because someone is afraid of it (no judgment please)

---

src/Metadata/Model/SourceFieldOption.php

ESPP-687 Fix createSourceFieldOptionLabel result hydration errors

---

src/Metadata/Resources/config/validator/validation.yaml
src/Metadata/Tests/Api/Rest/SourceFieldTest.php

ESPP-676 fix typo on error message

---

src/Index/DataTransformer/InstallIndexDataTransformer.php
src/Index/Resources/config/services.yaml

ESPP-688 Fix [Rest] Index installation: index is not refreshed

---

src/Entity/Filter/RangeFilterWithDefault.php
src/Search/DataProvider/Facet/ConfigurationCollectionDataProvider.php
src/Search/Model/Facet/Configuration.php
src/Search/Repository/Facet/ConfigurationRepository.php

ESPP-667 Add filters on FacetConfiguration model

---

src/Index/Model/Index/Mapping.php
src/Index/Service/IndexOperation.php
src/Metadata/EventSubscriber/SpreadSourceFieldData.php
src/Metadata/Tests/Unit/EventSubscriber/SpreadSourceFieldDataTest.php
src/Search/Elasticsearch/Builder/Request/Query/Fulltext/SearchableFieldFilter.php
src/Search/Tests/Api/GraphQl/SearchDocumentsTest.php
src/Search/Tests/fixtures/source_field.yaml

To be merge after : https://github.com/Elastic-Suite/gally-standard/pull/28

Feat bug weight select

---

composer.json
src/Catalog/DataProvider/LocalizedCatalogGroupOptionDataProvider.php
src/Catalog/Model/Source/LocalizedCatalogGroupOption.php
src/Catalog/Resources/config/services.yaml
src/Catalog/Tests/Api/GraphQl/LocalizedCatalogGroupOptionTest.php
src/Catalog/Tests/Api/Rest/LocalizedCatalogGroupOptionTest.php
src/DependencyInjection/Configuration.php
src/DependencyInjection/Extension.php
src/DependencyInjection/GallyExtension.php
src/Migrations/Resources/config/services.yaml
src/Migrations/Version/GallyComparator.php
src/Migrations/Version20230119101706_Initial_Schema.php
src/Validator/DateRange.php
src/Validator/Resources/translations/validators.en.xlf
src/Validator/Resources/translations/validators.fr.xlf

#1196129 Add boosts

---

src/Test/AbstractEntityTestWithUpdate.php

Fix content type of PUT queries on 'Gally test framwork'

---

src/Product/DataProvider/ProductDataProvider.php
src/Product/Resources/config/services.yaml
src/RuleEngine/Service/RuleEngineManager.php
src/Search/Resources/config/services.yaml
src/Search/Service/SearchContext.php

#1191187 Add search context

---

src/Catalog/Resources/config/doctrine/Catalog.orm.xml
src/Category/Model/Category/Configuration.php
src/Metadata/Model/SourceField.php
src/RuleEngine/EventSubscriber/ClearRuleCache.php
src/RuleEngine/Resources/config/services.yaml
src/RuleEngine/Service/RuleEngineManager.php
src/RuleEngine/Tests/Unit/EventSubscriber/ClearRuleCache.php
src/RuleEngine/Tests/fixtures/metadata.yaml

#1191187 Cache the result when we transform rule to gally filters

---

src/Catalog/Tests/Api/GraphQl/Source/LocalizedCatalogGroupOptionTest.php
src/Hydra/Decoration/Serializer/DocumentationNormalizer.php

Add a way to enrich Hydra documentation for classes in APIResources

---

src/Index/Dto/Bulk/Request.php
src/Product/Decoration/CategoryData/SyncCategoryNameAfterBulkRest.php
src/Product/Resources/config/services.yaml
src/Product/Service/CategoryNameUpdater.php
src/Product/Tests/Unit/Service/CategoryNameUpdaterTest.php

Use bulk query to update category name attribute on product indexation

Fix 1237100 bulk update

---

src/RuleEngine/Resources/config/services.yaml
src/RuleEngine/Service/RuleEngineManager.php

Fix display all products if virtual rule is broken

---

src/Locale/DataProvider/Source/LocaleGroupOptionDataProvider.php

Remove unsupported locale from the endpoint /locale_group_options

---

src/Configuration/Resources/config/doctrine.yaml

#1246648 [Doctrine] Register date function

---

src/Product/GraphQl/Type/Definition/SortInputType.php
src/Search/GraphQl/Type/Definition/SortInputType.php
src/Search/Resources/config/services.yaml

#1254015 Add 'nested filter' for category attributes

---

.github/workflows/ci.yml
.github/workflows/qa.yml

Replace on workflow files 1.0.x branch by a pattern

---

src/Configuration/Resources/config/api_platform.yaml

Update API version to 1.1.0

---

src/Category/DataFixtures/fixtures/source_field.yaml
src/Search/Elasticsearch/Builder/Request/SortOrder/SortOrderBuilder.php
src/Search/Resources/config/services.yaml
src/Search/Tests/Api/GraphQl/SearchDocumentsTest.php
src/Search/Tests/Unit/Elasticsearch/Adapter/Common/Request/SortOrder/AssemblerTest.php
src/Search/Tests/Unit/Elasticsearch/Builder/Request/SimpleRequestBuilderTest.php
src/Search/Tests/Unit/Elasticsearch/Builder/Request/SortOrder/SortOrderBuilderTest.php

#1244748 fix sort order on documents GraphQl query

---

src/Product/DataProvider/ProductDataProvider.php
src/Product/Model/Product.php
src/Product/Resources/config/gally.yaml
src/Product/Resources/config/services.yaml
src/Product/Tests/Api/GraphQl/SearchPreviewProductsTest.php
src/Product/Tests/Api/GraphQl/SearchProductsTest.php

 #1259178 Add previewProduct GrapQL query

---

src/Catalog/DataPersister/LocalizedCatalogDataPersister.php
src/Catalog/Tests/Api/Rest/LocalizedCatalogsTest.php
src/Product/DataProvider/Facet/OptionDataProvider.php
src/Product/DataProvider/ProductDataProvider.php
src/Product/Resources/config/services.yaml
src/Product/Service/GraphQl/FilterManager.php
src/Search/DataProvider/DocumentDataProvider.php
src/Search/DataProvider/Facet/OptionDataProvider.php

Fixes #1262483 category

---

src/Metadata/Controller/AddSourceFieldOptions.php
src/Metadata/DataPersister/SourceFieldDataPersister.php
src/Metadata/DataPersister/SourceFieldOptionDataPersister.php
src/Metadata/EventSubscriber/SpreadSourceFieldData.php
src/Metadata/Model/SourceField.php
src/Metadata/Model/SourceFieldLabel.php
src/Metadata/Model/SourceFieldOption.php
src/Metadata/Model/SourceFieldOptionLabel.php
src/Metadata/Resources/config/services.yaml
src/Metadata/Tests/Api/Rest/SourceFieldOptionTest.php
src/Metadata/Tests/Api/Rest/SourceFieldTest.php
src/Metadata/Tests/fixtures/source_field.yaml
src/Test/AbstractEntityTest.php

Todo : 
- Fix front attribut configuration page

[SourceField] #1230533 - Mass update source field option

---

.github/actions/init-env/action.yml
.github/workflows/ci.yml
.github/workflows/qa.yml
src/Search/Resources/config/gally.yaml

[Search] Rename request type labels

---

src/Configuration/Resources/config/services.yaml
src/Search/OpenSearch/ClientBuilder.php
src/Search/Resources/config/services.yaml

Create a custom opensearch client builder in order to be able to extend it in other bundles

Feat opensearch custom builder

---

src/Index/Command/IndexClearCommand.php

Avoid to remove specific elasticsearch indices

Fix clean index

---

src/Search/Elasticsearch/Adapter/Common/Request/Query/Assembler/FunctionScore.php
src/Search/Elasticsearch/Request/Query/FunctionScore.php
src/Search/Tests/Unit/Elasticsearch/Request/Query/FunctionScoreTest.php

[VectorSearch] #1241202 Add min score in function_score query

---

src/Index/Service/IndexSettings.php
src/Index/Tests/Unit/IndexManagerTest.php
src/Menu/Resources/translations/menu.en.xlf
src/Menu/Resources/translations/menu.fr.xlf
src/Search/Tests/Unit/Elasticsearch/Request/Container/RelevanceConfigurationTest.php

Feat add vector translation

---

src/Product/Serializer/ProductDenormalizer.php
src/Search/DataProvider/Paginator.php
src/Search/Elasticsearch/Adapter.php
src/Search/Elasticsearch/Request.php
src/Search/Elasticsearch/RequestInterface.php
src/Search/Model/Document.php

[Search] #1245816 Add ElasticSearch query in request object

---

src/Search/Elasticsearch/Adapter/Common/Request/Query/Assembler/FunctionScore.php
src/Search/Serializer/DocumentDenormalizer.php

- Don't extend native denormalizer, we should use a custom denormalizer in llm context
- Prevent adding empty min_score in search query

Revert [Documents] Extends support of Documents denormalizer

---

src/Analysis/Tests/Unit/ConfigTest.php
src/Analysis/Tests/Unit/ConfigurationMock.php
src/DependencyInjection/Configuration.php
src/DependencyInjection/GallyExtension.php
src/Index/Resources/config/services.yaml
src/Index/Service/IndexSettings.php
src/Index/Tests/Unit/IndexSettingsTest.php
src/Search/Model/IngestPipeline.php
src/Search/Repository/Ingest/PipelineRepository.php
src/Search/Repository/Ingest/PipelineRepositoryInterface.php
src/Search/Resources/config/gally.yaml
src/Search/Resources/config/services.yaml
src/Search/Resources/config/test/gally.yaml
src/Search/Service/IngestPipelineProcessorProvider.php
src/Search/Tests/Unit/Repository/IngestPipelineRepositoryTest.php

#1241202 - Add ingest pipeline management

---

.github/actions/init-env/action.yml

[CI] Fix github action definition

---

src/Product/DataFixtures/fixtures/system_source_field.yaml
src/Product/DataFixtures/sample_data/source_field.yaml

[Product] Add description source field as system source field

---

src/Cache/Service/CacheManager.php
src/Product/Tests/Api/GraphQl/SearchProductsTest.php
src/Product/Tests/fixtures/source_field.yaml
src/Search/Tests/Api/GraphQl/SearchDocumentsTest.php

[Search] #1281647 Improve Fulltext Search Unit Tests

---

src/Fixture/Resources/config/services.yaml
src/Fixture/Service/ORMPsqlSequenceProvider.php
src/Metadata/Model/SourceField.php
src/Product/DataFixtures/fixtures/system_source_field.yaml

Sometime it is useful to be able to be able to define an entity increment id before persisting the entity (if we want to assign this id to another entity field)

[Fixture] Add sequence function in fixtures

---

src/Metadata/Model/SourceField.php
src/Metadata/Tests/Api/Rest/SourceFieldTest.php

[Autocomplete] #1295278 Force autocomplete attribute to be filterable

---

src/Locale/Tests/Api/GraphQl/Source/LocaleGroupOptionTest.php
src/Locale/Tests/Api/Rest/Source/LocaleGroupOptionTest.php

Add tests on locale_group_options api

---

src/Catalog/Resources/config/services.yaml
src/Catalog/State/Source/LocalizedCatalogGroupOptionProvider.php
src/Category/Controller/CategoryConfigurationGet.php
src/Category/Entity/Category/Configuration.php
src/Category/Resources/config/services.yaml

…rations/category/{categoryId}' API

Fix wrong category configuration iri

---

src/Category/Service/CategorySynchronizer.php
src/Category/Tests/Api/GraphQl/CategorySynchronizerTest.php

[Category] Fix update category configurations on index install

---

src/Metadata/GraphQl/Type/Definition/Filter/DateTypeFilterInputType.php
src/Product/Tests/Api/GraphQl/SearchProductsTest.php
src/Product/Tests/fixtures/product_documents.json
src/Search/Elasticsearch/Adapter/Common/Request/Query/Assembler/DateRange.php
src/Search/Elasticsearch/Builder/Request/Query/Filter/FilterQueryBuilder.php
src/Search/Elasticsearch/Request/Query/GeoDistance.php
src/Search/GraphQl/Type/Definition/Filter/DistanceFilterInputType.php
src/Search/GraphQl/Type/Definition/Filter/EqualTypeFilterInputType.php
src/Search/Resources/config/services.yaml
src/Search/Resources/config/test/gally.yaml
src/Search/Tests/Api/GraphQl/SearchDocumentsTest.php
src/Search/Tests/Unit/Elasticsearch/Adapter/Common/Request/Query/Assembler/DateRangeTest.php
src/Search/Tests/Unit/Elasticsearch/Adapter/Common/Request/Query/Assembler/GeoDistanceTest.php
src/Search/Tests/Unit/Elasticsearch/Request/Query/GeoDistanceTest.php
src/Search/Tests/fixtures/documents.json

Feat filter date eq

---

src/Metadata/GraphQl/Type/Definition/Filter/LocationTypeFilterInputType.php
src/Product/Tests/Api/GraphQl/SearchProductsTest.php
src/Search/Elasticsearch/Builder/Request/Query/Filter/FilterQueryBuilder.php

[Filter] #1305713 - Manage stiching for location filter

---

src/Metadata/Entity/SourceField.php

fix(#1317656): No Filters for 'use spannable query' field

---

src/Product/Tests/Api/GraphQl/ProductSortingOptionTest.php
src/Search/Entity/Source/SortingOption.php
src/Search/Service/SortingOptionsProvider.php
src/Search/Tests/Api/GraphQl/SortingOptionTest.php

[Sort] #1306485 - Add type to sorting options

---

src/Index/MutationResolver/CreateIndexMutation.php
src/Index/Service/SelfReindexOperation.php
src/Index/State/CreateIndexProcessor.php

[Index] Do not "hide" index creation error

---

src/Category/Tests/Api/GraphQl/CategorySynchronizerTest.php

fix(#1320974): Duplicate index during sync category tests

---

src/Category/Service/CategorySynchronizer.php
src/Category/Tests/Api/GraphQl/CategorySynchronizerTest.php

[Category] #1326012 - Validate category name and add explicite message

---

src/Security/OpenApi/JwtDecorator.php

[OpenApi] Make token api the first in swagger

---

src/Cache/Resources/config/services.yaml
src/Configuration/Resources/config/api_platform.yaml

feat(#1305734): Give the possibility to disable varnish

---

src/Menu/Resources/translations/menu.en.xlf
src/Menu/Resources/translations/menu.fr.xlf

chore(#1316100): [Menu]Rename 'Catalog Structure' to 'Results'

---

src/Category/Resources/config/services.yaml
src/Category/Service/CategoryTreeBuilder.php
src/Category/Tests/Api/GraphQl/CategoryTreeTest.php
src/Category/Tests/fixtures/product_category.json
src/Product/Resources/config/elasticsearch/request_type.yaml
src/Search/Elasticsearch/Request/Aggregation/Provider/CategoryCountAggregationProvider.php
src/Search/Resources/config/elasticsearch/request_type.yaml
src/Search/Resources/config/services.yaml

[Category Tree] #1328246 - Add product count in category tree api

---

src/GraphQl/Error/ErrorHandler.php
src/GraphQl/Resources/config/services.yaml

[GraphQl] Log exceptions in GraphQl context because it's not done by default

---

src/Index/Tests/Unit/Converter/SourceField/SourceFieldConverterTest.php
src/Metadata/Entity/SourceField.php
src/Metadata/EventSubscriber/ValidateSourceFieldProperties.php
src/Metadata/Tests/Api/Rest/SourceFieldTest.php

Make search analyzer updatable for source field with type 'reference'

---

.github/workflows/ci.yml

https://github.com/Elastic-Suite/gally-standard/security/dependabot/3

Update gituhub action version

---

src/Search/Resources/config/gally.yaml

fix(#1335198): Boosts are not applied to autocomplete

---

src/Metadata/Entity/SourceField.php

[Source field grid] Add filter 'Analyzer'

---

src/Product/Decoration/GraphQl/AddEntityTypeInContext.php
src/Product/State/ProductProvider.php
src/Search/State/DocumentProvider.php
src/Search/State/Paginator.php

[Search] #1285437 - Add container config in result object

---

src/Search/State/Facet/ConfigurationItemProvider.php
src/Search/Tests/Api/Rest/FacetConfigurationTest.php
src/Search/Tests/fixtures/categories.yaml
src/Search/Tests/fixtures/category_configurations.yaml
src/Search/Tests/fixtures/facet_configuration.yaml

Fix category id with hyphen

---

src/Metadata/Controller/BulkSourceFieldOptions.php
src/Metadata/Controller/BulkSourceFields.php
src/Metadata/Resources/config/services.yaml
src/Metadata/Validator/SourceFieldDataValidator.php

[Cache] Purge varnish on bulk insert

---

src/Metadata/Entity/SourceField.php
src/Metadata/Entity/SourceFieldOption.php
src/Metadata/Tests/Api/Rest/SourceFieldOptionTest.php
src/Metadata/Tests/Api/Rest/SourceFieldTest.php

[Metadata] Remove label from sourceField and sourceFieldOption API

---

src/Category/Resources/config/doctrine/Category.Configuration.orm.xml
src/Category/Resources/config/doctrine/Category.orm.xml
src/Migrations/Version20250709141342_Fix_category_column_type.php

[Category] Update category column type to allow long value

---

src/Search/Tests/Api/GraphQl/RequestTypeOptionTest.php
src/Search/Tests/Api/Rest/RequestTypeOptionTest.php

[Configuration] #1316095 - Fix wrong namespace

---

src/Catalog/Tests/Api/Rest/CatalogsTest.php
src/Catalog/Tests/Api/Rest/LocalizedCatalogsTest.php
src/Catalog/Tests/Api/Rest/Source/LocalizedCatalogGroupOptionTest.php
src/Catalog/Tests/Unit/DefaultCatalogProviderTest.php
src/Category/Tests/Api/Rest/CategoryConfigurationTest.php
src/Category/Tests/Api/Rest/CategoryTest.php
src/Configuration/Resources/config/doctrine.yaml
src/Configuration/Resources/config/doctrine/Configuration.orm.xml
src/Configuration/Resources/config/test/doctrine_migrations.yaml
src/Configuration/Tests/Api/Rest/ConfigurationTest.php
src/DependencyInjection/Extension.php
src/Doctrine/Type/JsonbType.php
src/Index/Tests/Api/Rest/IndexOperationsTest.php
src/Metadata/Tests/Api/Rest/MetadataTest.php
src/Metadata/Tests/Api/Rest/SourceFieldLabelTest.php
src/Metadata/Tests/Api/Rest/SourceFieldOptionLabelTest.php
src/Metadata/Tests/Api/Rest/SourceFieldOptionTest.php
src/Metadata/Tests/Api/Rest/SourceFieldTest.php
src/Search/Tests/Api/GraphQl/FacetConfigurationTest.php
src/Search/Tests/Api/Rest/FacetConfigurationTest.php
src/Test/AbstractEntityTestCase.php
src/Test/AbstractTestCase.php
src/Test/Migrations/Version20250826152243_Add_test_schema.php
src/User/Resources/config/doctrine/User.orm.xml
src/User/Tests/Api/Rest/UserTest.php

[Test] #1340400 - Build test db from migration

---

src/Product/Entity/Facet/Option.php
src/Product/Tests/Api/GraphQl/ViewMoreFacetTest.php
src/Search/Entity/Facet/Option.php
src/Search/State/Facet/OptionProvider.php
src/Search/Tests/Api/GraphQl/ViewMoreFacetTest.php

[Facet] #1346775 - Search in facet options

---

src/Metadata/GraphQl/Type/Definition/Filter/DateTypeFilterInputType.php
src/Metadata/Resources/config/services.yaml
src/Product/Tests/Api/GraphQl/SearchProductsTest.php
src/RuleEngine/Service/RuleType/AttributeRule.php
src/RuleEngine/Tests/Api/Rest/RuleEngineOperatorsTest.php
src/Search/Elasticsearch/Adapter/Common/Request/Query/Assembler/DateRange.php
src/Search/Elasticsearch/Builder/Request/Query/Filter/FilterQueryBuilder.php
src/Search/GraphQl/Type/Definition/Filter/DistanceFilterInputType.php
src/Search/GraphQl/Type/Definition/Filter/EqualTypeFilterInputType.php
src/Search/GraphQl/Type/Definition/Filter/RangeFilterInputType.php
src/Search/Resources/config/services.yaml
src/Search/Service/DateFormatUtils.php
src/Search/Tests/Api/GraphQl/SearchDocumentsTest.php
src/Search/Tests/Unit/Elasticsearch/Adapter/Common/Request/Query/Assembler/DateRangeTest.php
src/Search/Tests/Unit/Service/DateFormatUtilsTest.php

[Boost] #1349469 - Add Date SourceField in Rule
